### ISSUE TITLE
Fields using keys rather than labels as column names

### ISSUE THREAD

**Issue by dasads44** [spikeheap/labking#73] opened 2015-06-23 16:36 UTC
Certain fields in a dataset are using the keys rather than the labels as the column names. The labels are used correctly in the modals but the key values are used in the grid view in LabKing and in the LabKey dataset grid view. 

This issue has only appeared in numerical fields which have been added after the dataset was initially created.

**Comment by spikeheap** [comment] 2015-06-30 15:27
Hi @dasads44, I can't reproduce this in 15.1 with the latest version of LabKing, so it may have been resolved already.

Using the EAP export, I was looking at the `CD4` and `e GFR` fields. The labels appear to be correct for both the table view and the edit modal. 

We had some issues with labels/names a couple of weeks ago so that may be an artefact of that. Let's test it on the next release.

**Comment by spikeheap** [comment] 2015-07-14 14:37
Closing for now as it seems to work on development. I think there's an open ticket with LabKey, so we can always re-open this if it's still an issue on 15.1.

**Closed by spikeheap** 2015-07-14 14:37 UTC
